// Fuente sintetica para ejercitar el sync worker sin dependencias externas.
//
// Diseño: 12 ofertas total — 4 validas + 8 rechazos. Cada caso de rechazo es
// IDENTICO a una oferta valida excepto por el campo que ejercita su validacion
// objetivo. Esto garantiza que un fallo de smoke test apunta a UNA validacion
// y no a un cocktail.
//
// Cobertura por validacion (ver worker/validate.js):
//   mock-005 -> V11 descuento bajo umbral
//   mock-006 -> V16 sin stock
//   mock-007 -> V6 affiliate_url ausente
//   mock-008 -> V13 sin imagenes
//   mock-009 -> V12 is_on_sale no es true
//   mock-010 -> V10 descuento ficticio (current >= original)
//   mock-011 -> V14 gender invalido
//   mock-012 -> V15 currency invalida
//
// Llamadas sucesivas a fetch() devuelven el mismo dataset, lo que hace que la
// segunda corrida del worker sea idempotente: 0 entered, 0 exited, 0 updated.

export const name = 'mock'

export async function fetch() {
  return [
    // ── 4 ofertas validas (deberian entrar a verified_offers) ────────────
    {
      external_id: 'mock-001',
      sku: 'MOCK-HOODIE-BLK',
      title: 'Essentials Heavy Hoodie — Black',
      brand: 'Recall Mock Co',
      description: 'Algodon pesado 400 GSM, fit relajado.',
      category: 'Tops',
      gender: 'men',
      images: ['https://example.com/img/hoodie-blk.jpg'],
      current_price: 1399,
      original_price: 1999,
      currency: 'MXN',
      store_id: 'mock-store-a',
      store_name: 'Mock Store A',
      affiliate_url: 'https://aff.example.com/r/mock-001',
      direct_url: 'https://store-a.example.com/p/hoodie-blk',
      country_availability: ['MX', 'CO'],
      sizes_available: ['S', 'M', 'L', 'XL'],
      in_stock: true,
      is_on_sale: true,
    },
    {
      external_id: 'mock-002',
      sku: 'MOCK-AIRTRAIL-WHT',
      title: 'Air Trail Low — White',
      brand: 'Mockswoosh',
      description: 'Trail runner urbana.',
      category: 'Footwear',
      gender: 'unisex',
      images: ['https://example.com/img/airtrail-wht.jpg'],
      current_price: 1100,
      original_price: 2000,
      currency: 'MXN',
      store_id: 'mock-store-a',
      store_name: 'Mock Store A',
      affiliate_url: 'https://aff.example.com/r/mock-002',
      direct_url: 'https://store-a.example.com/p/airtrail-wht',
      country_availability: ['MX'],
      sizes_available: ['7', '8', '9', '10', '11'],
      in_stock: true,
      is_on_sale: true,
    },
    {
      external_id: 'mock-003',
      sku: 'MOCK-PUFFER-OLV',
      title: 'Cropped Puffer — Olive',
      brand: 'Recall Mock Co',
      description: 'Puffer cropped, relleno sintetico.',
      category: 'Outerwear',
      gender: 'women',
      images: ['https://example.com/img/puffer-olv.jpg'],
      current_price: 1600,
      original_price: 4000,
      currency: 'MXN',
      store_id: 'mock-store-b',
      store_name: 'Mock Store B',
      affiliate_url: 'https://aff.example.com/r/mock-003',
      direct_url: 'https://store-b.example.com/p/puffer-olv',
      country_availability: ['MX', 'CO'],
      sizes_available: ['XS', 'S', 'M'],
      in_stock: true,
      is_on_sale: true,
    },
    {
      external_id: 'mock-004',
      sku: 'MOCK-BOXTEE-WHT',
      title: 'Box Logo Tee — White',
      brand: 'Mockswoosh',
      description: 'Tee logo box, algodon peinado.',
      category: 'Tops',
      gender: 'men',
      images: ['https://example.com/img/boxtee-wht.jpg'],
      current_price: 779,
      original_price: 999,
      currency: 'MXN',
      store_id: 'mock-store-b',
      store_name: 'Mock Store B',
      affiliate_url: 'https://aff.example.com/r/mock-004',
      direct_url: 'https://store-b.example.com/p/boxtee-wht',
      country_availability: ['MX'],
      sizes_available: ['S', 'M', 'L'],
      in_stock: true,
      is_on_sale: true,
    },

    // ── 8 ofertas que deben ser rechazadas, una por validacion ───────────

    // mock-005 -> V11: descuento 15% (bajo umbral 20%)
    {
      external_id: 'mock-005',
      sku: 'MOCK-SLIMJEAN-IND',
      title: 'Slim Jeans — Indigo',
      brand: 'Mockswoosh',
      description: 'Slim fit, indigo crudo.',
      category: 'Bottoms',
      gender: 'men',
      images: ['https://example.com/img/slimjean-ind.jpg'],
      current_price: 850,
      original_price: 1000,
      currency: 'MXN',
      store_id: 'mock-store-a',
      store_name: 'Mock Store A',
      affiliate_url: 'https://aff.example.com/r/mock-005',
      direct_url: 'https://store-a.example.com/p/slimjean-ind',
      country_availability: ['MX'],
      sizes_available: ['30', '32', '34', '36'],
      in_stock: true,
      is_on_sale: true,
    },

    // mock-006 -> V16: in_stock false
    {
      external_id: 'mock-006',
      sku: 'MOCK-TRUCKER-BLK',
      title: 'Trucker Cap — Black',
      brand: 'Recall Mock Co',
      description: 'Cap trucker mesh.',
      category: 'Accessories',
      gender: 'unisex',
      images: ['https://example.com/img/trucker-blk.jpg'],
      current_price: 390,
      original_price: 600,
      currency: 'MXN',
      store_id: 'mock-store-a',
      store_name: 'Mock Store A',
      affiliate_url: 'https://aff.example.com/r/mock-006',
      direct_url: 'https://store-a.example.com/p/trucker-blk',
      country_availability: ['MX'],
      sizes_available: ['OS'],
      in_stock: false,
      is_on_sale: true,
    },

    // mock-007 -> V6: omite affiliate_url
    {
      external_id: 'mock-007',
      sku: 'MOCK-BEANIE-GRY',
      title: 'Ribbed Beanie — Grey',
      brand: 'Recall Mock Co',
      description: 'Beanie ribbed lana merino.',
      category: 'Accessories',
      gender: 'unisex',
      images: ['https://example.com/img/beanie-gry.jpg'],
      current_price: 250,
      original_price: 500,
      currency: 'MXN',
      store_id: 'mock-store-b',
      store_name: 'Mock Store B',
      direct_url: 'https://store-b.example.com/p/beanie-gry',
      country_availability: ['MX', 'CO'],
      sizes_available: ['OS'],
      in_stock: true,
      is_on_sale: true,
    },

    // mock-008 -> V13: images vacio
    {
      external_id: 'mock-008',
      sku: 'MOCK-TANK-NVY',
      title: 'Mesh Tank — Navy',
      brand: 'Mockswoosh',
      description: 'Tank mesh perforada.',
      category: 'Tops',
      gender: 'men',
      images: [],
      current_price: 350,
      original_price: 500,
      currency: 'MXN',
      store_id: 'mock-store-a',
      store_name: 'Mock Store A',
      affiliate_url: 'https://aff.example.com/r/mock-008',
      direct_url: 'https://store-a.example.com/p/tank-nvy',
      country_availability: ['MX'],
      sizes_available: ['S', 'M', 'L'],
      in_stock: true,
      is_on_sale: true,
    },

    // mock-009 -> V12: is_on_sale false
    {
      external_id: 'mock-009',
      sku: 'MOCK-SANDAL-BRN',
      title: 'Strap Sandal — Brown',
      brand: 'Recall Mock Co',
      description: 'Sandalia con strap de cuero.',
      category: 'Footwear',
      gender: 'unisex',
      images: ['https://example.com/img/sandal-brn.jpg'],
      current_price: 600,
      original_price: 800,
      currency: 'MXN',
      store_id: 'mock-store-b',
      store_name: 'Mock Store B',
      affiliate_url: 'https://aff.example.com/r/mock-009',
      direct_url: 'https://store-b.example.com/p/sandal-brn',
      country_availability: ['MX'],
      sizes_available: ['7', '8', '9', '10'],
      in_stock: true,
      is_on_sale: false,
    },

    // mock-010 -> V10: current_price >= original_price (descuento ficticio)
    {
      external_id: 'mock-010',
      sku: 'MOCK-BELT-BLK',
      title: 'Leather Belt — Black',
      brand: 'Mockswoosh',
      description: 'Cinturon de cuero hebilla acero.',
      category: 'Accessories',
      gender: 'unisex',
      images: ['https://example.com/img/belt-blk.jpg'],
      current_price: 600,
      original_price: 400,
      currency: 'MXN',
      store_id: 'mock-store-a',
      store_name: 'Mock Store A',
      affiliate_url: 'https://aff.example.com/r/mock-010',
      direct_url: 'https://store-a.example.com/p/belt-blk',
      country_availability: ['MX'],
      sizes_available: ['80', '85', '90', '95'],
      in_stock: true,
      is_on_sale: true,
    },

    // mock-011 -> V14: gender fuera del set cerrado
    {
      external_id: 'mock-011',
      sku: 'MOCK-SCARF-RED',
      title: 'Wool Scarf — Red',
      brand: 'Recall Mock Co',
      description: 'Bufanda lana 100%.',
      category: 'Accessories',
      gender: 'other',
      images: ['https://example.com/img/scarf-red.jpg'],
      current_price: 600,
      original_price: 1000,
      currency: 'MXN',
      store_id: 'mock-store-b',
      store_name: 'Mock Store B',
      affiliate_url: 'https://aff.example.com/r/mock-011',
      direct_url: 'https://store-b.example.com/p/scarf-red',
      country_availability: ['MX', 'CO'],
      sizes_available: ['OS'],
      in_stock: true,
      is_on_sale: true,
    },

    // mock-012 -> V15: currency 5 letras (no es ISO de 3)
    {
      external_id: 'mock-012',
      sku: 'MOCK-GLOVE-WHT',
      title: 'Knit Glove — White',
      brand: 'Mockswoosh',
      description: 'Guante tejido punto fino.',
      category: 'Accessories',
      gender: 'women',
      images: ['https://example.com/img/glove-wht.jpg'],
      current_price: 750,
      original_price: 1000,
      currency: 'PESOS',
      store_id: 'mock-store-a',
      store_name: 'Mock Store A',
      affiliate_url: 'https://aff.example.com/r/mock-012',
      direct_url: 'https://store-a.example.com/p/glove-wht',
      country_availability: ['MX'],
      sizes_available: ['S', 'M'],
      in_stock: true,
      is_on_sale: true,
    },
  ]
}
